# Numpy Crash Course

In [3]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

In [7]:
import sys 
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

## Creating Arrays

In [10]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [12]:
type(my_list)

list

In [14]:
arr = np.array(my_list) 

In [16]:
arr

array([0, 1, 2, 3, 4, 5])

In [18]:
type(arr)

numpy.ndarray

In [20]:
type(my_list)

list

In [22]:
np. # we learn important function 

SyntaxError: invalid syntax (1655120754.py, line 1)

In [24]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
np.arange(3.0)  

array([0., 1., 2.])

In [28]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int32)

In [36]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [38]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [40]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [42]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int32)

In [44]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [46]:
np.arange(10,10) 

array([], dtype=int32)

In [48]:
np.arange()

TypeError: arange() requires stop to be specified.

In [49]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [52]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [54]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [56]:
np.zeros(3) # parameter  tunning 

array([0., 0., 0.])

In [58]:
np.zeros(5, dtype=int) # hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [60]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [62]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [64]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [66]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [70]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [74]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [78]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [80]:
n

(6, 7)

In [82]:
n1

(6, 8)

In [84]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [86]:
np.ones(3)

array([1., 1., 1.])

In [88]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [90]:
np.ones(4)

array([1., 1., 1., 1.])

In [92]:
n

(6, 7)

In [94]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [96]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [98]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [100]:
np.twos((2,3)) 

AttributeError: module 'numpy' has no attribute 'twos'

In [102]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [104]:
np.ones(2)

array([1., 1.])

In [106]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [108]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [110]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [112]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [114]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [116]:
range(5)

range(0, 5)

In [118]:
r = range(5)
r

range(0, 5)

In [120]:
for i in r:
    print(i)

0
1
2
3
4


In [122]:
list(range(5))

[0, 1, 2, 3, 4]

In [124]:
range(1,10)

range(1, 10)

In [126]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [128]:
list(range(1,10,3))

[1, 4, 7]

In [130]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [132]:
rand(3,2)

NameError: name 'rand' is not defined

In [134]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [136]:
np.random.rand(5)

array([0.48778369, 0.29746155, 0.83340062, 0.19605849, 0.14472295])

In [138]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [140]:
np.random.rand(2,4)

array([[0.26617115, 0.37692506, 0.60829116, 0.28442122],
       [0.11351494, 0.68142801, 0.69892873, 0.62646414]])

In [142]:
np.random.randint(2,4)

2

In [144]:
np.random.randint(2,20) # 2nd argument is exlusive 

18

In [146]:
np.random.randint(0,1) 

0

In [148]:
np.random.randint(10,20,5)

array([19, 16, 13, 12, 11])

In [150]:
np.random.randint(1,6,4)

array([5, 4, 1, 2])

In [152]:
np.random.rand(3)

array([0.19643133, 0.19028658, 0.07397062])

In [154]:
np.random.randint(1)  

0

In [156]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [158]:
np.random.randint(-30,20,10) 

array([ 13, -22, -25, -12,  16, -19, -11, -15, -11, -24])

In [160]:
np.random.randint(20,30,10) 

array([23, 23, 23, 21, 21, 22, 23, 26, 29, 25])

In [162]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

5

In [164]:
np.random.randint(10,21,3)

array([10, 20, 16])

In [166]:
np.random.randint(1,12,10)

array([3, 3, 5, 7, 1, 4, 6, 7, 5, 7])

In [168]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

array([[24, 16, 21, 10, 29, 25, 22, 13, 15, 13],
       [35, 12, 21, 13, 14, 26, 20, 11, 12, 36],
       [38, 22, 14, 34, 37, 38, 18, 21, 24, 27],
       [39, 10, 15, 29, 21, 32, 34, 25, 15, 30],
       [19, 31, 17, 28, 31, 22, 35, 12, 19, 32],
       [33, 31, 33, 34, 33, 15, 20, 37, 11, 31],
       [28, 13, 28, 30, 31, 15, 29, 21, 29, 33],
       [34, 10, 31, 19, 33, 21, 37, 35, 17, 18],
       [31, 21, 13, 39, 39, 33, 11, 35, 14, 37],
       [24, 37, 13, 19, 11, 37, 29, 33, 27, 21]])

In [170]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

array([[61, 84, 23, 63, 38, 15, 94, 57, 34, 92, 83, 82],
       [35,  3, 72, 35, 98, 88, 70, 10, 40, 65, 63, 36],
       [52, 50, 82, 89, 68, 69, 95, 93, 80, 42,  5, 20],
       [65, 61, 13, 28, 71, 14, 97, 98, 98, 90, 18, 25],
       [91, 82, 30, 96, 25, 77, 23, 22, 62, 21, 24, 58],
       [75, 71, 60, 91, 56, 93, 19, 93, 42, 81, 92, 26],
       [ 6, 75,  6, 86, 24, 30, 95, 43, 35, 80, 71, 21],
       [69, 73, 65, 44, 95, 45,  6, 31,  5, 58, 67, 86],
       [35, 18, 20, 13, 74, 10, 95, 43, 12, 25, 38,  5],
       [89, 66, 39, 45, 58, 33, 86, 31, 10, 81, 55, 39],
       [13, 70, 62, 75, 69, 27, 75, 49, 27, 71, 77,  8],
       [94, 44, 67, 47, 94, 63,  4, 99, 65, 75, 68,  1]])

In [172]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [174]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [176]:
b = np.random.randint(10,20,(5,4))
b

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

In [178]:
type(b)

numpy.ndarray

In [180]:
b

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

In [182]:
b[:] 

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

In [184]:
b[1:3]

array([[16, 11, 11, 17],
       [15, 16, 10, 15]])

In [186]:
b

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

In [188]:
b[1,2]

11

In [190]:
b

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

In [192]:
b[1,3]

17

In [194]:
b[1,-1]

17

In [196]:
b

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

In [198]:
b[2:3]

array([[15, 16, 10, 15]])

In [200]:
b

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

In [202]:
b[0:-2] 

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15]])

In [204]:
b

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

In [206]:
b[0,2] 

14

In [208]:
b

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

In [210]:
b[-5,-3] 

14

In [212]:
b

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

In [214]:
b[-4,2] 

11

In [216]:
np.random.randint(10,20,(4,4))

array([[19, 14, 19, 12],
       [15, 10, 18, 18],
       [14, 16, 19, 16],
       [18, 10, 14, 10]])

In [218]:
b 

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

In [220]:
b[-4,-2]

11

In [222]:
b

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

In [224]:
b[-4:2] 

array([[16, 11, 11, 17]])

In [226]:
b[:]

array([[12, 14, 14, 16],
       [16, 11, 11, 17],
       [15, 16, 10, 15],
       [13, 19, 13, 15],
       [15, 17, 17, 16]])

## Operations

In [229]:
a = np.random.randint(10,20,10)
a

array([17, 18, 13, 16, 14, 16, 11, 19, 18, 19])

In [231]:
id(a)

2319064970128

In [233]:
arr

array([0, 1, 2, 3, 4, 5])

In [235]:
arr2 = np.random.randint(0,100,(10,10))

In [237]:
arr2

array([[95, 44, 45, 15, 57, 55, 27, 69,  2, 77],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61],
       [49, 50,  1, 27,  7, 76, 37, 53, 12, 98],
       [38, 32, 19, 45, 40,  5, 24, 59,  3, 68],
       [ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88]])

In [239]:
arr

array([0, 1, 2, 3, 4, 5])

In [241]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [243]:
arr

array([0, 1, 2, 3, 4, 5])

In [245]:
arr[:4] 

array([0, 1, 2, 3])

In [247]:
arr2[:]

array([[95, 44, 45, 15, 57, 55, 27, 69,  2, 77],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61],
       [49, 50,  1, 27,  7, 76, 37, 53, 12, 98],
       [38, 32, 19, 45, 40,  5, 24, 59,  3, 68],
       [ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88]])

In [249]:
arr2[0:5] 

array([[95, 44, 45, 15, 57, 55, 27, 69,  2, 77],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35]])

In [251]:
arr2

array([[95, 44, 45, 15, 57, 55, 27, 69,  2, 77],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61],
       [49, 50,  1, 27,  7, 76, 37, 53, 12, 98],
       [38, 32, 19, 45, 40,  5, 24, 59,  3, 68],
       [ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88]])

In [253]:
arr2[1,4] 

47

In [255]:
arr2

array([[95, 44, 45, 15, 57, 55, 27, 69,  2, 77],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61],
       [49, 50,  1, 27,  7, 76, 37, 53, 12, 98],
       [38, 32, 19, 45, 40,  5, 24, 59,  3, 68],
       [ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88]])

In [257]:
arr2[-5,5] 

61

In [259]:
arr2[-5,-5] 

61

In [261]:
arr2

array([[95, 44, 45, 15, 57, 55, 27, 69,  2, 77],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61],
       [49, 50,  1, 27,  7, 76, 37, 53, 12, 98],
       [38, 32, 19, 45, 40,  5, 24, 59,  3, 68],
       [ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88]])

In [263]:
arr2[-5,-5]

61

In [265]:
arr2

array([[95, 44, 45, 15, 57, 55, 27, 69,  2, 77],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61],
       [49, 50,  1, 27,  7, 76, 37, 53, 12, 98],
       [38, 32, 19, 45, 40,  5, 24, 59,  3, 68],
       [ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88]])

In [267]:
arr2[-1,-2]

37

In [269]:
arr2

array([[95, 44, 45, 15, 57, 55, 27, 69,  2, 77],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61],
       [49, 50,  1, 27,  7, 76, 37, 53, 12, 98],
       [38, 32, 19, 45, 40,  5, 24, 59,  3, 68],
       [ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88]])

In [271]:
arr2[::-1]

array([[ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88],
       [38, 32, 19, 45, 40,  5, 24, 59,  3, 68],
       [49, 50,  1, 27,  7, 76, 37, 53, 12, 98],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [95, 44, 45, 15, 57, 55, 27, 69,  2, 77]])

In [273]:
arr2

array([[95, 44, 45, 15, 57, 55, 27, 69,  2, 77],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61],
       [49, 50,  1, 27,  7, 76, 37, 53, 12, 98],
       [38, 32, 19, 45, 40,  5, 24, 59,  3, 68],
       [ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88]])

In [275]:
arr2[::-2] 

array([[ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88],
       [49, 50,  1, 27,  7, 76, 37, 53, 12, 98],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99]])

In [277]:
arr2

array([[95, 44, 45, 15, 57, 55, 27, 69,  2, 77],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61],
       [49, 50,  1, 27,  7, 76, 37, 53, 12, 98],
       [38, 32, 19, 45, 40,  5, 24, 59,  3, 68],
       [ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88]])

In [279]:
arr2[::-3]

array([[ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [95, 44, 45, 15, 57, 55, 27, 69,  2, 77]])

In [281]:
arr2

array([[95, 44, 45, 15, 57, 55, 27, 69,  2, 77],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61],
       [49, 50,  1, 27,  7, 76, 37, 53, 12, 98],
       [38, 32, 19, 45, 40,  5, 24, 59,  3, 68],
       [ 0, 67, 87, 78, 36, 40, 13, 70, 37, 88]])

In [283]:
arr2[:-3] 

array([[95, 44, 45, 15, 57, 55, 27, 69,  2, 77],
       [64, 98, 89, 49, 47, 76, 33, 85, 38, 99],
       [48, 38, 31, 74, 55, 76, 93, 64, 23, 68],
       [64, 52, 94, 77, 82, 40, 53, 74, 22, 85],
       [ 3, 68, 62, 57, 83, 10, 54, 71, 21, 35],
       [ 7, 89, 99, 56, 75, 61, 22, 80, 31, 37],
       [95, 96, 99,  4, 28, 35, 84, 65, 81, 61]])

In [285]:
arr

array([0, 1, 2, 3, 4, 5])

In [287]:
arr.max() 

5

In [289]:
arr.min()

0

In [291]:
arr

array([0, 1, 2, 3, 4, 5])

In [293]:
arr.mean()

2.5

In [295]:
arr

array([0, 1, 2, 3, 4, 5])

In [297]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [299]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

# Without work on import* can you please find the median, mode)

In [302]:
arr

array([0, 1, 2, 3, 4, 5])

In [304]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [306]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [308]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [310]:
arr

array([0, 1, 2, 3, 4, 5])

In [312]:
arr.reshape(2,4) 

ValueError: cannot reshape array of size 6 into shape (2,4)

In [314]:
arr

array([0, 1, 2, 3, 4, 5])

In [316]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [318]:
arr.reshape(2,3,order='F') # print element with fortran 

array([[0, 2, 4],
       [1, 3, 5]])

In [320]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [322]:
arr

array([0, 1, 2, 3, 4, 5])

In [324]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [326]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [328]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [330]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [332]:
arr.reshape(2,6) 

ValueError: cannot reshape array of size 6 into shape (2,6)

In [334]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [336]:
arr

array([0, 1, 2, 3, 4, 5])

In [338]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

## Indexing

In [341]:
mat = np.arange(0,100).reshape(10,10) 

In [343]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [345]:
row = 4
col = 5

In [347]:
col

5

In [349]:
row

4

In [351]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [353]:
mat[row,col] 

45

In [355]:
mat[4,5] 

45

In [357]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [359]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [361]:
col = 6

In [363]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [365]:
mat[6] # befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [367]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [369]:
# With Slices
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [371]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [373]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [375]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [377]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [379]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [381]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [383]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [385]:
row

4

In [387]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [389]:
mat[:row]  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [391]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [393]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [395]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [397]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [399]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [401]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [403]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [405]:
row

4

In [407]:
col

6

In [409]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [411]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [413]:
mat[1,4]

14

In [415]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [417]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [419]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [421]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [423]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [425]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [427]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [429]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [431]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [433]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [435]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [437]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [439]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [441]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [443]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [445]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [447]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [449]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [451]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [453]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [455]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [457]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [459]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [461]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [463]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [465]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [467]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [469]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [471]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [473]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [475]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [477]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [479]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [481]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [483]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [485]:
mat[0,1]

1

In [487]:
mat[1,6]

16

In [489]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [491]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [493]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [495]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [497]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [499]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [501]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [503]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [505]:
mat[3,5]

35

In [507]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [509]:
mat[1:2,2:4] 

array([[12, 13]])

In [511]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [513]:
mat[2:3,2:3] 

array([[22]])

In [515]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [517]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [519]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [521]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [523]:
mat[2:3,4:5]

array([[24]])

## Masking

In [526]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [528]:
id(mat)

2319070942128

In [530]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [532]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [534]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [536]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [538]:
mat[mat==50] 

array([50])

In [540]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [542]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [544]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [546]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [548]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [550]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [552]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [554]:
a4 = mat[mat==50]
a4

array([50])

# python program to generat otp 

In [557]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 0452


In [559]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [561]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [563]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x0000021BF351BC00>


In [565]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
