In [1]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [5]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

In [7]:
# creating Arrays

In [9]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [11]:
type(my_list)

list

In [13]:
# list to array

In [17]:
# !pip install numpy

In [19]:
arr =  np.array(my_list)

In [21]:
arr

array([0, 1, 2, 3, 4, 5])

In [23]:
type(arr)

numpy.ndarray

In [25]:
type(my_list)

list

In [29]:
# np. # we learn  imporant function

In [31]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
np.arange(3.0)

array([0., 1., 2.])

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [39]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
np.arange(20,10)

array([], dtype=int32)